config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  def search
    if params[:search].blank?
      redirect_to flats_path
    else
      @query = params[:search].downcase
      @flats = Flat.where('lower(name) LIKE :search', search: "%#{@query}%")
    end
  end

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render new_flat_path
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy

    redirect_to flats_path, status: :see_other
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit flat details</h1>

  <%= render "form", flat: @flat %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1 class="mt-4 mb-4">All our Flats (<%= @flats.size %>)</h1>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-sm-4">
        <div class="card mb-4">
          <img src=<%= flat.picture_url %> class="card-img-top" style="height: 180px" alt="">
          <div class="card-body">
            <div class="card-details">
              <h5 class="card-title"><%= flat.name %></h5>
              <p class="card-text"><%= flat.address %></p>
              <div class="card-icons">
                <i class="fa-solid fa-user-group"> <%= flat.number_of_guests %></i>
                <i class="fa-solid fa-sterling-sign"> <%= flat.price_per_night %></i>
              </div>
            </div>
            <div class="card-actions">
              <p><%= link_to "More info", flat_path(flat) %></p>
              <p><%= link_to "Edit", edit_flat_path(flat), style: "color: orange" %></p>
              <p><%= link_to "Remove", flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, style: "color: red" %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>Add a new flat</h1>

<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/search.html.erb
<div class="container">
  <h1 class="mt-4 mb-4">Found (<%= @flats.size %>) flats</h1>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-sm-4">
        <div class="card mb-4">
          <img src=<%= flat.picture_url %> class="card-img-top" style="height: 180px" alt="">
          <div class="card-body">
            <div class="card-details">
              <h5 class="card-title"><%= flat.name %></h5>
              <p class="card-text"><%= flat.address %></p>
              <div class="card-icons">
                <i class="fa-solid fa-user-group"> <%= flat.number_of_guests %></i>
                <i class="fa-solid fa-sterling-sign"> <%= flat.price_per_night %></i>
              </div>
            </div>
            <div class="card-actions">
              <p><%= link_to "More info", flat_path(flat) %></p>
              <p><%= link_to "Edit", edit_flat_path(flat), style: "color: orange" %></p>
              <p><%= link_to "Remove", flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, style: "color: red" %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="header-image" style="background-image: url(<%= @flat.picture_url %>);"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="card card-show mb-4">
        <div class="card-body">
          <h1 class="card-title card-show-title"><%= @flat.name %></h1>
          <p class="card-text card-show-text"><%= @flat.address %></p>
        </div>
      </div>
      <div class="card card-show card-show-details mb-4">
        <div class="card-body">
          <h3>A bit more about this flat...</h3>
          <p class="card-title"><%= @flat.description %></p>
          <div class="map"></div>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card card-show mb-4">
        <div class="card-body">
          <h4 class="card-title">Book this place!</h4>
          <form action="">
            <div class="input-group">
              <span class="input-group-text">From:</span>
              <input type="text" class="form-control" placeholder="14/08/20123" aria-label="start-date" aria-describedby="start-date-label">
            </div>
            <div class="input-group mt-2">
              <span class="input-group-text">To:</span>
              <input type="text" class="form-control" placeholder="20/08/2023" aria-label="end-date" aria-describedby="start-date-label">
            </div>
            <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
          </form>
        </div>
      </div>
      <div class="card card-show mb-4">
        <div class="card-body">
          <h4 class="card-title">Details</h4>
          <p class="card-text"><%= @flat.number_of_guests %> people &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp £<%= @flat.price_per_night %></p>
        </div>
      </div>
      <div class="card card-show mb-4">
        <div class="flex-align">
          <h4 class="no-mb">Share</h4>
          <div class="flex">
            <i class="fa-brands fa-facebook"></i>
            <i class="fa-brands fa-twitter"></i>
            <i class="fa-brands fa-instagram"></i>
            <i class="fa-brands fa-reddit"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.4.2/css/all.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to "Simple Airbnb", flats_path, class: "navbar-brand" %>
      <div class="ms-auto d-flex">
        <%= form_tag(search_flats_path, method: "get", class: "d-flex") do %>
          <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
          <%= button_tag "Search", class: "btn btn-outline-success my-2 my-sm-0 ms-2" %>
        <% end %>
        <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary ms-2" %>
      </div>
    </div>
  </nav>
  <%= yield %>
  </body>
</html>